### PR TITLE
Implement support for git-annex / datalad clone and push

### PR DESCRIPTION
**Pull request by nellh**
This includes all the backend support needed to allow bidirectional interaction with datasets via git.

Includes:
* HTTP ref and pack endpoints.
* API to generate short lived git access tokens.
* Git credentials helper script to automatically obtain a token if you have an unexpired CLI login.
* Load balancer configuration.
* Better handling for expired tokens in general.

Excluded:
* Cache updates should work but validation does not automatically run. This is a separate issue being solved in #1893
* Pre-receive validation.
* Any UI or documentation for this feature.

### CODE REVIEW

**Review by david-nishi — APPROVED** [review]
missed broken pytests

**Review by david-nishi — CHANGES_REQUESTED** [review]
## Tested:
-  javascript test suite passing
- update dataset file from browser and cli
- update dataset with git push to openneuro remote
- successfully fail to update dataset file with invalid token from cli

It's just a couple of the datalad service tests not passing (test_draft 1 and test_upload 2). Rest looks good.

**Comment by nellh** [comment]
> ## Tested:
> 
>     * javascript test suite passing
> 
>     * update dataset file from browser and cli
> 
>     * update dataset with git push to openneuro remote
> 
>     * successfully fail to update dataset file with invalid token from cli
> 
> 
> It's just a couple of the datalad service tests not passing (test_draft 1 and test_upload 2). Rest looks good.

Thanks, I broke cookie auth and didn't have that test enabled locally. It's fixed now, good that we have coverage for that in the upload tests :+1:

**Review by david-nishi — APPROVED** [review]
All tests are passing and git push to openneuro remote looks good.

**Pull request merged**
