### PR TITLE
Server: Refactor API key handler for reusability.

### PR DESCRIPTION
**Pull request by nellh**
This moves the API key out of the handler and into libs/apikey.js to allow several modules to import just the apikey functions without the handlers. Adds a getUserIdFromApiKey to lookup users during auth and test coverage for libs/apikey.js.

### CODE REVIEW

**Comment by nellh** [comment]
Made a few more changes here, switching to a better hashing library with promises and proper salting.

**Comment by jstiehl** [comment]
Guessing you are aware of this but there are merge conflicts that need to be resolved.

**Comment by nellh** [comment]
Fixed that. I didn't notice it - I am extracting these commits from another branch and must have missed that change.

**Comment by jstiehl** [comment]
other than the styling issue this looks good to me.  Were you planning on making a separate issue for the styling? If so, I can approve this PR now.  Let me know.
image

**Review by jstiehl — APPROVED** [review]

**Pull request merged**
