### PR TITLE
fix(ssr): Use cache-and-network for drafts

### PR DESCRIPTION
**Pull request by nellh**
Prevents SSR cache age from displaying incorrect drafts after load.

### CODE REVIEW

**Comment by tranttommy** [comment]
I don't know if it's related, but when I upload a dataset and then try to view it, I see the dataset page for a brief moment but then it automatically refreshes a couple of times and then it turns into this:
Screen Shot 2021-05-14 at 11 57 21

When I go to "My Datasets", this happens: 
Screen Shot 2021-05-14 at 11 56 47

**Comment by nellh** [comment]
> I don't know if it's related, but when I upload a dataset and then try to view it, I see the dataset page for a brief moment but then it automatically refreshes a couple of times and then it turns into this:
> Screen Shot 2021-05-14 at 11 57 21
> 
> When I go to "My Datasets", this happens:
> Screen Shot 2021-05-14 at 11 56 47

Not related, we should have an issue for this though. It's caused by bids-validator@1.7.1 + the Vite dev server.

**Comment by tranttommy** [comment]
This is working with the merge of #2133

**Comment by ckrountree** [comment]
@franklin-feingold  This should address the issue with ds001705.

**Pull request merged**
