### PR TITLE
track My Datasets and My Bookmarks state in URL query params

### PR DESCRIPTION
**Pull request by david-nishi**
## Major Changes
- Clicking to / away from My Datasets updates the url query param mydatasets.
- Removing the My Datasets chiclet removes mydatasets from the url query params.
- Clicking to / away from My Bookmarks updates the url query param bookmarks.
- Removing the My Bookmarks chiclet removes bookmarks from the url query params.

### CODE REVIEW

**Review by thinknoack — APPROVED** [review]

**Comment by ckrountree** [comment]
Gitlab 321

**Review by nellh — COMMENTED** [review]
Maybe it would be better to just add these as URLs and detect them as routes? That way there's no URL manipulation logic needed in these search components.

**Review by thinknoack — CHANGES_REQUESTED** [review]
removed approval to discuss @nellh comments

**Comment by david-nishi** [comment]
Closed in favor of route param approach.

**Pull request closed without merging**
