### PR TITLE
feat(app): Add Neurosift viewer for EDF and NWB files

### PR DESCRIPTION
**Pull request by nellh**
Implementation of #3186 using the iframe approach.

Screenshot From 2024-10-31 10-22-40

### CODE REVIEW

**Comment by magland** [comment]
Thanks @nellh 

This won't work as is for NWB files. The URL for those looks a bit different:

https://neurosift.app/?p=/nwb&url=https://api.dandiarchive.org/api/assets/027567cf-e9e0-4aba-83c0-ef2d22c8c1b7/download/

Notice the p=/nwb instead of p=/edf

**Comment by magland** [comment]
I wonder what's the best way to select the height. Is the plan to just fix it as something sensible?

**Comment by nellh** [comment]
> Thanks @nellh
> 
> This won't work as is for NWB files. The URL for those looks a bit different:
> 
> https://neurosift.app/?p=/nwb&url=https://api.dandiarchive.org/api/assets/027567cf-e9e0-4aba-83c0-ef2d22c8c1b7/download/
> 
> Notice the p=/nwb instead of p=/edf

Thanks, fixed!

> I wonder what's the best way to select the height. Is the plan to just fix it as something sensible?

I set it to 50% viewport height as this is what our HTML iframe viewer was doing already and generally gives a good amount of space for the viewer without using a static height.

**Comment by magland** [comment]
This is great, thanks @nellh . When will this go live?

**Comment by nellh** [comment]
> This is great, thanks @nellh . When will this go live?

It will be included in the next OpenNeuro release, aiming to release early next week.

**Comment by magland** [comment]
@nellh I think there's a problem here. It seems that when you visit the page of an EDF file, the entire file gets automatically downloaded to the browser before the iframe is rendered. This is probably because that's how other file types are handled. But in this case, we don't need the file to be downloaded - and that's the point of neurosift - that's it's lazy-loading. Sometimes the files can be quite large.

**Pull request merged**
