### PR TITLE
Issue 226

### PR DESCRIPTION
**Pull request by Xesme**
This is a fix for issue #226, where users were unable to see all file directories. In addition, this PR updates select arrows within the jobs modal.

### CODE REVIEW

**Comment by chrisgorgo** [comment]
Not sure if this information is relevant, but the original issue was with displaying dataset files not files that are part of job outputs.

**Comment by Xesme** [comment]
Indeed. The dataset file tree is a child of div.dataset-inner by adjusting the bottom margin on the parent you force the overflow children to be visible. :)

**Comment by Xesme** [comment]
Hmm. Yes that is helpful. Thank you!

**Comment by chrisgorgo** [comment]
Awesome. Thanks for clarifying!

Best,
Chris

**Comment by Xesme** [comment]
Double checked this fix. Please let me know if the file tree remains hidden. Checked fix on chrome and firefox.

**Pull request merged**
