### PR TITLE
fixing responsive issues for logged in

### PR DESCRIPTION
**Pull request by thinknoack**
fixes issues for https://gitlab.com/squishymedia/nimh/openneuropet/-/issues/292

### CODE REVIEW

**Comment by ckrountree** [comment]
- [ ] Modality portals are missing the `+` icon in the gray 'add' box.
- [ ] The carets are now squares (maybe okay).
- [x] Black bar with text (footer) under the facets section.

Screen Shot 2021-07-19 at 5 07 24 PM

**Comment by thinknoack** [comment]
fixed the overlay for the footer 

but the other errors are not present and seem to be an issue with your local. try a `docker-compose down && docker-compose up`?

**Review by nellh — APPROVED** [review]
Tested this as well and not seeing the other two issues.

**Comment by ckrountree** [comment]
Tried docker-compose down && docker-compose up.  Don't see the other two issues any longer.

**Review by ckrountree — APPROVED** [review]

**Pull request merged**
