### PR TITLE
Clarification of the grace period

### PR DESCRIPTION
**Pull request by chrisgorgo**

### CODE REVIEW

**Comment by chrisgorgo** [comment]
@nellh it seems that Circle is comparing the rendered page to a snapshot and that's why tests are failing. How can I update the snapshots?

**Comment by nellh** [comment]
'jest -u' or 'yarn test -u' will update the snapshots.

**Comment by chrisgorgo** [comment]
This should be ready to merge.

**Comment by chrisgorgo** [comment]
@nellh I don't see this update on production: https://openneuro.org/faq Caching issue?

**Comment by nellh** [comment]
@chrisfilo I should have checked this more closely, sorry. It looks like you edited the testing snapshot and I reverted it when I updated the snapshot based on the current code. The FAQ is defined in `faq/faq.jsx`. I'll move the FAQ changes to the component and do a new release to update this.

The other disclaimer change did get deployed.

**Comment by nellh** [comment]
@chrisfilo This is fixed and deployed again.

**Comment by chrisgorgo** [comment]
Thanks!

Best,
Chris

**Pull request merged**
