### PR TITLE
[WIP] search

### PR DESCRIPTION
**Pull request by rwblair**
#372 

@chrisfilo put the search bar only where datasets are listed:
screen shot 2018-02-07 at 9 37 07 am

Is this ok? or should it be some where more prominent?

@nellh I have the gcse code in the didmount call, is there a more appropriate place it should live?

Switching between the dataset list and the analyses tab and back again will sometimes cause the searchbar to not show up, but toggling again it will come back. Still trying to figure out why this is happening.

### CODE REVIEW

**Comment by chrisgorgo** [comment]
Search results in the future will also include available apps (pending #288). Might be worth putting the search panel (maybe folded?) in the nav bar. @Xesme @jstiehl @olgn any ideas how this could be done in aesthetically pleasing way?

**Comment by nellh** [comment]
This is going to cause issues with the virtual DOM. It appears/disappears as you navigate sometimes because React removes the markup on re-render and this is timing dependent.

It would be better to use the [custom search REST API](https://developers.google.com/custom-search/json-api/v1/using_rest) and add a component that renders an input text box for search, then takes you to a new route with the results once you submit your search (/search/[query]). You would have two components GoogleSearch and GoogleSearchResults. The simplest way to do this is pass the query as part of the route to the results component, make the search request in the GoogleSearchResults componentDidMount  and display a loading state until the query results came back.

You could make a new search store but it isn't needed and would complicate the implementation.

**Comment by nellh** [comment]
I took a look at this so far and I have some suggestions.

The page load can be avoided when you make a search by using a controlled input component instead of a form. You use withRouter to get access to the history prop, then calling history.push() with the query on submit. React router provides a helper here so you can define the route as `<Route name="search" path="/search/:query" component={SearchResults} />` then get the query in the SearchResults component with a `match.params.query` prop.

To avoid the page load when clicking a result, you have to extract the relative URL and use the Link component. I'd check if `window.location` is defined and return an anchor if the search result URL doesn't match the current protocol/hostname and Link with the relative URL if it does. Both are needed in case search results include a URL outside of the React app (like a file inside a dataset or testing the site on alternate origins).

One other thing I noticed is `{search()}` is not equivalent to `<Search />` because the JSX transform actually calls React.createElement when you specify a JSX component. It will work either way but `<Search />` is preferred - it makes it easier to debug what's going on with tools that recognize components and easier to write tests for.

**Comment by rwblair** [comment]
Still need to add the window.location changes.

for the route I'm having the query be appended directly after '/search/' I think this still needs to be put into a GET param; right now searching for a full url does not work.

I moved the search component out of common/partials since that wasn't hot reloading on my local computer. Where should this component live in the end?

How should I trigger a re-render when the search button is hit? It works as expected on the dataset list pages, but on the search page it does not.

Finally still need to differentiate between waiting for a request to come back and no results.

**Comment by nellh** [comment]
I sent you some example code for the search button.

Partials was a good place for it. Are you developing on macOS? You might need the polling configuration from #386 to get webpack to pick up changed files automatically inside of Docker.

**Comment by rwblair** [comment]
closing due to #419

**Pull request closed without merging**
