### PR TITLE
Uploader

### PR DESCRIPTION
**Pull request by thinknoack**
adds the uploader component to the new site as well as styles to accommodate. This will be refactored in the future.

### CODE REVIEW

**Review by david-nishi — CHANGES_REQUESTED** [review]
Couple notes (don't need to be addressed in this PR):
- There isn't an indicator for upload progress, success, or failure for the redesign implementation yet.
- The dataset does not show up in search after upload until the indexer is triggered.

**Comment by nellh** [comment]
>     * The dataset does not show up in search after upload until the indexer is triggered.
For this, maybe we can just add the document (or a placeholder if not all info is available) after the initial upload?

**Review by nellh — CHANGES_REQUESTED** [review]
I think this really needs some kind of progress, even if it's only inside the modal.

The toast styles might need to be imported earlier in the tree for the redesign as well.

**Comment by ckrountree** [comment]
> I think this really needs some kind of progress, even if it's only inside the modal.
> 

We will definitely need a progress bar of some kind.  Let's do the MVP here and then address a fuller indicator post-beta.

**Review by david-nishi — APPROVED** [review]

**Comment by thinknoack** [comment]
> I think this really needs some kind of progress, even if it's only inside the modal.
> 
> The toast styles might need to be imported earlier in the tree for the redesign as well.

Just for clarification. 

Currently when a user uploads a dataset, the "UPLOAD" link changes to "View Details" that pops up a modal with a progress bar and the current files being uploaded. Not sure if there is a success/fail notice though. There is no longer a upload progress bar in the navbar. And we may want to add toast notification.

**Pull request merged**
