### PR TITLE
DOC: Replace outdated URL to DataLad docs

### PR DESCRIPTION
**Pull request by adswa**
Hi! :wave:
When browsing OpenNeuro I noticed that most links to DataLad documentation link to its homepage at http://datalad.org or the developer docs at http://docs.datalad.org.
We have migrated almost all user documentation for DataLad to [handbook.datalad.org](http://handbook.datalad.org).

This PR replaces an outdated link that does not resolve anymore. As a suggestion, I have linked it to our ["overview of DataLad"](http://handbook.datalad.org/en/latest/intro/executive_summary.html#executive-summary) page, but I would be happy to add a small section "Downloading OpenNeuro datasets" to the handbook if you're fine with that. In that case, please let me know, and I'll update the PR soon.

If it is okay with you, I would also replace links to datalad.org with links to handbook.datalad.org. Once you give me a go, I can add those changes to this PR (if this is the correct repo to do this).
Thanks in advance!

### CODE REVIEW

**Comment by adswa** [comment]
The test failures appear to be due to failing to provide a password to your workflows
```
#!/bin/bash -eo pipefail
docker login -u $DOCKER_USER -p $DOCKER_PASS

Password: EOF

Exited with code exit status 1

CircleCI received exit code 1
```

**Comment by effigies** [comment]
Thanks! If you're up for making a page for OpenNeuro users, that would be extremely valuable, IMO.

And +1 from me on replacing all links to datalad.org.

**Comment by adswa** [comment]
Cool, then I'll write that up and link it here, and replace datalad.org links. Please don't merge :)

**Comment by adswa** [comment]
The link is changed to [handbook.datalad.org/r.html?openneuro](https://handbook.datalad.org/r.html?openneuro), and the "read more about DataLad" frontpage link now points to the Handbook's [overview section](). This PR is done from my POV.

**Review by effigies — APPROVED** [review]
Lgtm. Thanks so much for writing that up!

**Pull request merged**
