### PR TITLE
add prominent dataset download button link

### PR DESCRIPTION
**Pull request by david-nishi**
Screen Shot 2019-04-30 at 16 18 37

### CODE REVIEW

**Review by nellh — CHANGES_REQUESTED** [review]
The old button should be removed and the style of the new button does not match the design spec.

**Comment by david-nishi** [comment]
@nell I talked with Kate about removing the old button and whether the new button styles should be consistent with the others or follow the design spec. Might be good to hash this out together @kate

**Comment by ckrountree** [comment]
@DaNish808 we can remove the download icon.  The style of the new button should mimic the old look in terms of radius - for consistency, I think (@nellh  - thoughts?).   However, the size should remain equivalent to the design spec.

**Comment by david-nishi** [comment]
Screen Shot 2019-05-02 at 10 27 25
Toolbar icon removed and style transitioned to new spec.

**Review by nellh — APPROVED** [review]

**Pull request merged**
