### PR TITLE
Improve Login Flow and UI

### PR DESCRIPTION
**Pull request by Xesme**
Ref:  #176 

@nellh - I started on improvements for issue 176. I added a 'what is this?' panel to the login modal with some info about ORCID. Let me know if there are adjustments to be made.

### CODE REVIEW

**Comment by nellh** [comment]
Merged in edee0778

**Comment by Xesme** [comment]
@nellh this pull request has been closed with unmerged commits, was this intended?

**Comment by nellh** [comment]
@Xesme I rebased the branch to fix the merge conflicts, so since it has a different parent, the merged commits are different than the ones in this branch.

**Comment by Xesme** [comment]
@nellh okay great! Is it ready for deletion?

**Pull request closed without merging**
