### PR TITLE
update core-js dependency, import polyfill

### PR DESCRIPTION
**Pull request by exbotanical**
Added core-js 3 as dependency so as to access and import the Object.fromEntries polyfill in the OpenNeuro App's entry point.

### CODE REVIEW

**Comment by exbotanical** [comment]
OK, fixed the package.json issue. Should be ready for approval!

**Comment by exbotanical** [comment]
I see the test failure and will take a look at that later today.

**Comment by exbotanical** [comment]
@nellh I'm not too familiar with codecov and how it interacts with / is affected by managing multiple packages. Any idea as to what might be causing this test failure?

David mentioned experiencing a similar issue with Lerna but doesn't recall the specifics, as it was quite a while ago. Maybe something to do with standardizing Yarn and not NPM?

**Comment by david-nishi** [comment]
That issue cropped up when trying to upgrade lerna to v3

**Pull request closed without merging**
