### PR TITLE
adding updates to fix responsive issues on front page

### PR DESCRIPTION
**Pull request by thinknoack**

### CODE REVIEW

**Comment by ckrountree** [comment]
### Landing Issues:

- [x] Login modal is cut off - affected in Galaxy Fold, iPhone X, 5/SE, & 6/7/8, Galaxy S5, Moto G4, and slightly but to a lesser extent in iPhone 6/7/8 Plus: 

Screen Shot 2021-07-16 at 5 21 43 PM

- [x] 'Get Updates' `subscribe` button needs top padding - affected all phones

Screen Shot 2021-07-16 at 5 27 40 PM

- [x] Should 'Get Updates' text line up with the left side of the input box?

Screen Shot 2021-07-16 at 5 31 14 PM

### WHAT WAS CHECKED in SEARCH:

- Checked all facets and some multiple additions (ie - Sr. PI).  
- Checked clearing some filters and clearing all filters --> if in a modality portal, clearing all takes the user back to Global search page.
- Checked clearing only modality filter but leaving all other all filters -->  takes the user back to Global search page.
- Checked `show filters` and `close filters`. 
- When entering a search term, the user can click the `+` or hit enter on the keyboard.

### Search Issue:

- [x] The number ranges (Age, Participants) are cut-off at 80 - no end is displayed, though the number increases - affected Galaxy Fold, iPhone 5/SE, Galaxy S5 and Moto 4 (but only slightly)

Screen Shot 2021-07-17 at 3 38 23 PM

### Other Issues:

- [x] Support page is cut off (to varying extents) - affected all except iPad and iPad Pro

Screen Shot 2021-07-17 at 4 09 14 PM

- [x] Do we want to to default to closed carets for the FAQ?  Other than that, FAQ - video link works, email link works, all other external links work

## NOTE
Opened ticket 287 to address PET-specific facets noticed during this review.

**Comment by thinknoack** [comment]
> * Login modal is cut off - affected in Galaxy Fold, iPhone X, 5/SE, & 6/7/8, Galaxy S5, Moto G4, and slightly but to a lesser extent in iPhone 6/7/8 Plus:
> 
> Screen Shot 2021-07-16 at 5 21 43 PM
> 
> * 'Get Updates' `subscribe` button needs top padding - affected all phones
> 
> Screen Shot 2021-07-16 at 5 27 40 PM
> 
> * Should 'Get Updates' text line up with the left side of the input box?
> 
> Screen Shot 2021-07-16 at 5 31 14 PM
> 
> * When going to the MRI portal, if I closed out of MRI, the page didn't take me anywhere.  This could have been my connection and not a real issue.  Checked Galaxy Fold here.
> 
> Opened ticket 287 to address PET-specific facets noticed during this review.

These are completed

**Comment by thinknoack** [comment]
>  Do we want to to default to closed carets for the FAQ? Other than that, FAQ - video link works, email link works, all other external links work

Currently on the prod site they are open (no even accordions) so I defaulted to open with new functionality for being able to collapse, if desired.

**Comment by thinknoack** [comment]
@ckrountree ready for re-review

**Comment by ckrountree** [comment]
- [x] Performance - The selected number range facet populations (reddish tag/labels) are fluttery for iPad Pro when the user drags to the correct number desired:

Screen Shot 2021-07-19 at 12 14 17 PM

- [x] Support ticket is still an issue (right side) for the Galaxy Fold, all iPhones, Galaxy S5 and Moto 4:

Screen Shot 2021-07-19 at 12 16 17 PM

**Pull request merged**
