### PR TITLE
Add checkboxes for disclaimer step during uploads

### PR DESCRIPTION
**Pull request by nellh**
Implements #1610 with an integration test for the behavior requiring one box to be checked to proceed.

Screenshot from 2020-10-19 21-55-27

### CODE REVIEW

**Comment by nellh** [comment]
Looking into the test failure here, seems to be a TypeScript setup issue rather than an issue with this PR.

**Review by david-nishi — APPROVED** [review]
## Tested:
- confirmed dataset upload prevented until a checkbox is clicked

**Comment by nellh** [comment]
@david-nishi I've added some additional changes to this to record the state for the checkboxes as dataset metadata fields during upload.

**Review by david-nishi — APPROVED** [review]
## Tested:
- submitted datasets with one and both checkboxes selected; confirmed expected results in database

**Pull request merged**
