### PR TITLE
1338 responsive filetree

### PR DESCRIPTION
**Pull request by exbotanical**
Note/reminder: These changes branch off of those introduced in #1337. I'll need to rebase this branch and remove the commits I took from #1337 (assuming #1337 has been merged into master) before merge.

### CODE REVIEW

**Comment by exbotanical** [comment]
Note/reminder: This issue relied heavily on some code already submitted for review. Before this is merged into master, I'll need to rebase this branch and remove the commits I took from #1337 (assuming #1337 has been merged into master) at [this PR](https://github.com/OpenNeuroOrg/openneuro/pull/1434).

**Comment by exbotanical** [comment]
Another note for future consideration: `matchMedia` - used in the custom media hook - is among the few [methods not implemented in JSDOM](https://jestjs.io/docs/en/manual-mocks#mocking-methods-which-are-not-implemented-in-jsdom). Jest has an official workaround that I've been using, but after a few times I wonder if we could (or more important, should) just add it to our Jest config as a mock, as discussed [here
](https://jestjs.io/docs/en/configuration.html#setuptestframeworkscriptfile-string).

**Review by david-nishi — APPROVED** [review]
looks good to me!

**Comment by exbotanical** [comment]
@david-nishi @ckrountree @MatthewZito Added an update so the file-tree is collapsed on mount.

**Review by david-nishi — APPROVED** [review]

**Comment by nellh** [comment]
@MatthewZito There's a merge conflict to resolve in this one before it can be merged.

**Pull request merged**
