### PR TITLE
1375 update file subscription

### PR DESCRIPTION
**Pull request by david-nishi**
Uploads and updates are now handled by the Apollo subscription model.

### CODE REVIEW

**Review by nellh — CHANGES_REQUESTED** [review]
The first file update works fine but a second file update of the same file or another file in the same tree breaks the file tree display and shows 'sub-01:anat:sub-01_T1w.nii.gz' and multiple copies.

**Comment by david-nishi** [comment]
Thanks Nell, should be fixed now

**Comment by david-nishi** [comment]
Thanks @nellh, should be fixed now

**Review by nellh — APPROVED** [review]
Looks good now.

**Comment by effigies** [comment]
Linking #1375

**Pull request merged**
