### PR TITLE
[Feature] ORCID oAuth2 flow

### PR DESCRIPTION
**Pull request by anibalsolon**
In order to support ORCID oAuth2 on OpenNeuro, this PR breaks the current auth flow into two providers (i.e. Google & ORCID) and implement the process to authenticate via ORCID. It also generalizes some implementations in order to support different auth providers.

Linked to https://github.com/OpenNeuroOrg/openneuro/issues/133
Depends on https://github.com/poldracklab/bids-core/pull/17

### CODE REVIEW

**Comment by nellh** [comment]
@anibalsolon Thank you for the contributions!

These changes look pretty good but I am running into a few issues:

* I initially got '{error: "Missing e-mail."}' back from the orcid endpoint because my email wasn't public but the error message displayed just says to try again later. I think this case is important to give some user feedback for it.
* Once I'd fixed my email privacy, I ran into ```DOMException: Blocked a frame with origin "http://localhost:9876" from accessing a cross-origin frame.
    at http://localhost:9876/app.bundle.js:108452:38``` on line 96 in orcid.js. Is the localhost path the issue here? FYI, we also have a dev server setup at https://openneuro.dev.sqm.io that I'd like to test on before production deployment and that might need to be configured.
* If a user was previously logged in with a Google account prior to these changes, this is not correctly handled after switching to this branch (navbar show non-functional login buttons and the upload dataset button when it shouldn't). It is working for me with a fresh browser session.

We've also merged another branch with some significant changes (React upgrade) so this will need to be rebased to merge.

**Comment by anibalsolon** [comment]
Hi @nellh !

About your points:
- ORCID does not provide any info if the e-mail is private. So I think that the message could comprehend both cases: user without email and user with private email; such as "Your account does not have an e-mail or your e-mail is not public. Please fix your account before continuing."
- It is an expected error since the script tries to read the current URL on the opened window used for ORCID sign-in. I will add a handler to this error. It is also a limitation for this auth flow, enforcing client and server to be exposed in the same domain:port (such as localhost:9876 or openneuro.org:80).
- I will try to reproduce this scenario, to understand the behavior.

**Comment by anibalsolon** [comment]
@nellh I have fixed the issues you mentioned and merged the upstream to my branch! I also pushed changes to bids-core repo.

Please let me know if it works properly now.

**Comment by nellh** [comment]
@anibalsolon Great, retested everything and all my test cases worked this time. Thanks again for the contributions!

**Comment by chrisgorgo** [comment]
Excellent! Thanks for your help!

**Comment by anibalsolon** [comment]
Awesome! Thank you for your reviews @nellh and @chrisfilo

**Pull request merged**
